---
bootstrap_url: http://mesos-boot:8888
cluster_name: dcos
exhibitor_storage_backend: static
ip_detect_filename: genconf/ip-detect
master_discovery: static
master_list:
- 192.168.0.1
resolvers:
- 8.8.4.4
- 8.8.8.8
superuser_password_hash:$6$rounds=656000$RtYnfkFXQodOBaLf$L.ACZ9iiX/skSQihcYdO1ENcOadtfg1BtqxzOX1ad2U6x7fWmwerhfve0zidIW60CjNe/ZLT4Mad7KuAEtZZs0
superuser_username:root

