#!/bin/bash

mkdir /opt/dcos-setup && cd /opt/dcos-setup && curl -O https://downloads.dcos.io/dcos/testing/master/dcos_generate_config.sh

mkdir -p genconf

cat > genconf/ip-detect << '__EOF__'
#!/usr/bin/env bash
set -o nounset -o errexit
export PATH=/usr/sbin:/usr/bin:$PATH
echo $(ip addr show enp2s0 | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
__EOF__

chmod 755 genconf/ip-detect

# your custom config file
cat > genconf/config.yaml << '__EOF__'

bootstrap_url: http://mesos-boot:8888
cluster_name: dcos
exhibitor_storage_backend: static
ip_detect_filename: genconf/ip-detect
master_discovery: static
master_list:
- 10.32.20.99
resolvers:
- 8.8.4.4
- 8.8.8.8
superuser_password_hash:$6$rounds=656000$RtYnfkFXQodOBaLf$L.ACZ9iiX/skSQihcYdO1ENcOadtfg1BtqxzOX1ad2U6x7fWmwerhfve0zidIW60CjNe/ZLT4Mad7KuAEtZZs0
superuser_username:root
__EOF__

bash dcos_generate_config.sh
