#! /bin/sh

yum install -y openssh-server openssh-clients openssh-askpass

sed -i 's/Port/#Port/' /etc/ssh/sshd_config
sed -i 's/PermitRootLogin/#PermitRootLogin/' /etc/ssh/sshd_config
sed -i 's/RSAAuthentication/#RSAAuthentication/' /etc/ssh/sshd_config
sed -i 's/X11Forwarding/#X11Forwarding/' /etc/ssh/sshd_config
echo "Port 1025" >> /etc/ssh/sshd_config

yum install -y policycoreutils-python

semanage port -a -t ssh_port_t -p tcp 1025

systemctl disable firewalld

systemctl restart sshd

