#!/bin/bash

# add docker repo and install docker
cat > /etc/yum.repos.d/docker.repo << '__EOF__'
[docker]
name=Docker Repository - Centos $releasever
baseurl=http://yum.dockerproject.org/repo/main/centos/$releasever
enabled=1
gpgcheck=1
gpgkey=http://yum.dockerproject.org/gpg
__EOF__
 
yum install docker-engine -y
yum clean all
 
mkdir -p /etc/systemd/system/docker.service.d 
 
cat > /etc/systemd/system/docker.service.d/override.conf << '__EOF__'
[Service] 
ExecStart= 
ExecStart=/usr/bin/docker daemon --storage-driver=overlay $DOCKER_NETWORK_OPTIONS -H fd:// 
__EOF__
 
systemctl daemon-reload
systemctl enable docker
 
#systemctl start docker
 
tee -a /etc/hosts << '__EOF__'
 
10.32.19.90   mesos-boot
 
10.32.19.92   mesos-master-01

10.32.21.239  mesos-agent-01
10.32.21.241  mesos-agent-02

__EOF__
 
yum install -y tar xz unzip curl ipset nfs-utils
yum clean all
 
groupadd nogroup
