#!/bin/bash

# add docker repo and install docker
yum update

cat > /etc/yum.repos.d/docker.repo << '__EOF__'

[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
__EOF__
 
yum install -y docker-engine-selinux-1.11.2-1.el7.centos
yum clean all

systemctl daemon-reload
systemctl start docker

systemctl enable docker
 
tee -a /etc/hosts << '__EOF__'
 
211.249.63.201  mesos-boot
 
175.158.15.45  mesos-master-01

10.32.20.73     mesos-agent-01
10.32.19.86     mesos-agent-02

__EOF__
 
yum install -y tar xz unzip curl ipset nfs-utils
yum clean all
 
groupadd nogroup
