#!/bin/bash

# add docker repo and install docker

cat > /etc/yum.repos.d/docker.repo << '__EOF__'

[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/7/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
__EOF__

cat > /etc/modules-load.d/overlay.conf << '__EOF__'
overlay
__EOF__

mkdir -p /etc/systemd/system/docker.service.d 
cat > /etc/systemd/system/docker.service.d/override.conf << '__EOF__'
[Service] 
ExecStart= 
ExecStart=/usr/bin/docker daemon --storage-driver=overlay -H fd:// 
__EOF__
 
systemctl daemon-reload
systemctl enable docker
 
#systemctl start docker
 
yum -y update
yum install -y docker-engine-1.11.2

yum install -y yum-versionlock
yum versionlock docker-engine

yum clean all

systemctl daemon-reload
systemctl start docker

systemctl enable docker
 
tee -a /etc/hosts << '__EOF__'
 
211.249.63.201  mesos-boot
 
175.158.15.45  mesos-master-01

10.32.20.80     mesos-agent-01
10.32.19.122     mesos-agent-02

__EOF__
 
yum install -y tar xz unzip curl ipset nfs-utils
yum clean all
 
groupadd nogroup
